[package]
name = "stressbench"
version = "0.1.0"
authors = ["Felipe Noronha <felipenoris@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
